# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Programs/Developing/Dig2_Pong_Joostens_Tomek/Dig2_Pong_Joostens_Tomek.srcs/sources_1/ip/blk_mem_gen_ball/blk_mem_gen_ball.xci
# IP: The module: 'blk_mem_gen_ball' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programs/Developing/Dig2_Pong_Joostens_Tomek/Dig2_Pong_Joostens_Tomek.srcs/sources_1/ip/blk_mem_gen_ball/blk_mem_gen_ball_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_ball'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Programs/Developing/Dig2_Pong_Joostens_Tomek/Dig2_Pong_Joostens_Tomek.srcs/sources_1/ip/blk_mem_gen_ball/blk_mem_gen_ball.xci
# IP: The module: 'blk_mem_gen_ball' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programs/Developing/Dig2_Pong_Joostens_Tomek/Dig2_Pong_Joostens_Tomek.srcs/sources_1/ip/blk_mem_gen_ball/blk_mem_gen_ball_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_ball'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
